### ISSUE TITLE
Escrowed funds of removed offers are lost

### ISSUE THREAD

**Issue by fiatjaf** [thorie7912/afb-public#53]
Happened with me:

1. I've opened a task
2. Someone posted an offer
3. I've accepted the offer and paid the escrow 
4. The offer was removed, I believe, so its value could be edited (amount was increased)
5. I've accepted the offer again and was prompted to pay the full escrow again, missing my previous payment

My lost payment details:

```yaml
id: 10
payment_hash: 6ed7b4ced55ce3507bdba7381df881658be8af5b929e245b4aae9e14aea9ff3e
destination: 038df0bd2fad1bfe42d177f18ea5e33543e2b855ef369d06bd94b81d2c87187c82
msatoshi: 10100000
msatoshi_sent: 10132987
created_at: 1542369365
status: complete
payment_preimage: 3205cad45f93e1f403e2e596a9c9296f18333c6d98e5a5cb1558a34d24948475
description: >-
  [Ask for Bitcoin] Payment of 10100 satoshi in accepting the offer from aloha
  for task: Record an ~10s screencast GIF
```
